export const INVOICES_KEY = "@invoices";
export const DATA_KEY = "@data";
export const CONFIG_KEY = "@config";

export const ConfigConstants = {
  NUMBER_OF_COLUMNS: "Количество колонок",
  FETCH_URL: "Api URL",
};

export const storageConstants = {
  SET_DATA: "SET_DATA",
  REMOVE_INVOICE: "REMOVE_INVOICE",
  REMOVE_ITEM: "REMOVE_ITEM",
  SAVE_EDIT_DATA: "SAVE_EDIT_DATA",
  SET_STORAGE_DATA: "SET_STORAGE_DATA",
  SET_STORAGE_DATA_FAILED: "SET_STORAGE_DATA_FAILED",
  SET_LOCAL_STORAGE: "SET_LOCAL_STORAGE",
  LOAD_LOCAL_STORAGE: "LOAD_LOCAL_STORAGE",
  LOAD_LOCAL_STORAGE_SUCCESS: "LOAD_LOCAL_STORAGE_SUCCESS",
  LOAD_ERROR: "LOAD_ERROR",
  SET_REMOTE_STORAGE: "SET_REMOTE_STORAGE",
  LOAD_REMOTE_STORAGE: "LOAD_REMOTE_STORAGE",
  LOAD_REMOTE_STORAGE_SUCCESS: "LOAD_REMOTE_STORAGE_SUCCESS",
  CHANGE_ORDER: "CHANGE_ORDER",
};
